#!/bin/bash

echo -e "To run type:\n./processed crx.data.training crx.data.testing\nRunning on $1 and $2..."

echo -e "\nOutputing processed data from $1 to crx.training.processed and $2 to crx.testing.processed"
python process_znorm.py $1 $2

